### ISSUE TITLE
Time arithmetic in Documentation incorrect?

### ISSUE THREAD

**Issue by ChristianKurz** [JeffreySarnoff/TimesDates.jl#11]
I didn't try the package yet, but this example from the Documentation seemed strange to me:

```julia
julia-> timedate = TimeDate(datetime)
2001-05-10T23:59:59.999

julia> timedate += Millisecond(1) + Nanosecond(1)
2001-05-10T00:00:00.000000001
```

I would expect this to yield

```julia
2001-05-11T00:00:00.000000001
```

**Comment by JeffreySarnoff** [comment]
yes -- you are right and the package does the right thing .. I have fixed
the typo
thank you for this
