### ISSUE TITLE
Differences with "Ultimate Datetime"

### ISSUE THREAD

**Issue by femtotrader** [JeffreySarnoff/TimesDates.jl#13]
Hello,

You may have seen Jay Dweck @ JuliaCon 2019
https://www.youtube.com/watch?v=HHjvv5yWMmc

What are differences between TimesDates and what he is trying to achieve?

Is there some discussion about creating a new package?

Kind regards

**Comment by JeffreySarnoff** [comment]
Kind regards back to you.
I have seen this.  ...

**Comment by JeffreySarnoff** [comment]
seems time slipped by -- UltimateDatetime is written in C and the Julia interface is one of several language interfaces -- generally speaking, they hew closer to the C code than each language style.
TimesDates is all about moving in the Julia mode.  Nothing new is happening, though I am open to it.
