### ISSUE TITLE
TimeDate(y, m, d, ...) constructor is too smart

### ISSUE THREAD

**Issue by dm3** [JeffreySarnoff/TimesDates.jl#23]
Having ran into https://github.com/JeffreySarnoff/TimesDates.jl/pull/22 I have to argue the basic constructor shouldn't be silently executing the spillover logic, but rather throwing on an improper value. Current logic is not aligned with how `Base.DateTime` works and can hide potentially serious bugs. 

Ideally there'd be a separate constructor version which would try to smartly adjust the values.  However, to preserve backwards compatibility I suggest adding a keyword parameter `;spill = true` and making the documentation very clear about the behaviour. When `;spill = false`, no spillover occurs and an exception is thrown on an out-of-range input value.

What do you think?

**Comment by JeffreySarnoff** [comment]
Thank you for considering improvements.  It has been some time since I reviewed this.  I will take another look and respond to this and to your PRs [very pleased that you provided PRs].

**Comment by JeffreySarnoff** [comment]
fixed
