### ISSUE TITLE
TimeDate should not assume a TimeZone

### ISSUE THREAD

**Issue by omus** [JeffreySarnoff/TimesDates.jl#4]
I think the definition of `timezone(x::TimeDate) = tzdefault()` is bad as it makes assumptions about what time zone a `TimeDate` is in. In my creation of TimeZones.jl a `DateTime` usually has an implicit associated time zone but in some cases you may want to refer to not an instant of time but rather a local time in any time zone. For example you may want to talk about noon today (2018-03-16T12:00) in Europe/London or Asia/Tokyo. The point is it is best for libraries like this not to make assumptions about the user's implicit time zone.

**Comment by JeffreySarnoff** [comment]
I agree, will fix.
I do find the availability of a settable default timezone helpful, that way the apps are not stuck in localtime without recourse.  Requiring an explicit setting of that prior to it becoming `readable` is reasonable.  Would that meet your concern?

**Comment by omus** [comment]
Since different authors may want to use different implicit time zones they would run into issues when both trying to set the `tzdefault`. I think you can make the local zone the default for `TimeDateZone` but I wouldn't use it for `TimeDate`.

**Comment by JeffreySarnoff** [comment]
ok

**Comment by JeffreySarnoff** [comment]
tzdefault cannot be set any more (preset to the local time zone, used rarely)

**Comment by JeffreySarnoff** [comment]
@omus Please explain what I have overlooked that causes the test on line 123 of runtests.jl to fail.

**Comment by JeffreySarnoff** [comment]
It had to do with what is corrected by parens
