### ISSUE TITLE
Make `DateTime(::TimeDate)` and `ZonedDateTime(::TimeDateZone)`

### ISSUE THREAD

**Issue by omus** [JeffreySarnoff/TimesDates.jl#5]
You could simplify and reduce duplicate code if you made the following functions:
```julia
DateTime(::TimeDate)
ZonedDateTime(::TimeDateZone)
```
For example you could use `ZonedDateTime(::TimeDateZone)` to remove several lines from your `astimezone`:
https://github.com/JeffreySarnoff/TimesDates.jl/blob/cdd6105018d438608d4705d333e4a0cd0f3f15f7/src/timezone/astimezone.jl#L7-L10

**Comment by JeffreySarnoff** [comment]
thanks

**Comment by JeffreySarnoff** [comment]
followed
