### ISSUE TITLE
Reinventing `Libc.TmStruct`?

### ISSUE THREAD

**Issue by omus** [JeffreySarnoff/TimesDates.jl#6]
I may be wrong but it looks to me that [`CTimeParts`](https://github.com/JeffreySarnoff/TimesDates.jl/blob/cdd6105018d438608d4705d333e4a0cd0f3f15f7/src/timesupport/ctime.jl#L21) is a duplicate of Base's [`Libc.TmStruct`](https://github.com/JuliaLang/julia/blob/277e6d5570383307d9a22993cc098ca98a3de614/base/libc.jl#L135).

**Comment by JeffreySarnoff** [comment]
Some of that file does copy Libc.TmStruct (the structure and initialization).    

I duplicated that part so the more substantive contribution would continue to work even in the event that accesses to Libc changes or ... come what may.

I wrote the code over a period of six months, and it took that long to formulate the generally easy-to-do universal_time to local_time and local_time to universal_time transformations.  As you know, there are some very strange combinations of state and environment that arise and often befuddle the intent of these mappings.  In addition to the problem of gapped transitions, there are a dozen or so issues relating to C library implementations, thread ignorance, and more that I recall as non-specific dark places to avoid.

That file is the only implementation I trust to be well-behaved and predictable   
 `universaltime --> localtime --> universaltime --> localtime`.

Some third party hardware paired with central clocks are good, too.  This is free.

**Comment by JeffreySarnoff** [comment]
_N_._B_.

   There are two additions that need to be introduced when its best for Julia.   
   They are not yet present because a design requirement is to avoid writing C.   
   This transformative property (universal_time mapsto local_time ...) must be
   multinstantiable , shardable , and each thread of it invisible to the others.

**Comment by JeffreySarnoff** [comment]
these comments have been transferred into the source file.
